name: Test coverage
on:
  push:
    branches:
      - develop
      - main
      - release/*

  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
      - converted_to_draft
      - ready_for_review
    branches:
      - develop
      - main
      - release/*

jobs:
  plan-sport-app:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.10 ]
    steps:
      - uses: actions/checkout@v1
      - name: install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run tests
        working-directory: .
        id: run-test
        run: pytest
      - name: run coverage
        working-directory: .
        id: run-coverage
        run: |
          pytest --cov=app
      - name: check coverage
        working-directory: .
        id: check-coverage
        run: |
          COVERAGE_THRESHOLD=70
          coverage=$(coverage report -m | tail -n 1 | awk '{print $4}' | tr -d %)
          if [ $coverage -ge $COVERAGE_THRESHOLD ]; then
            echo "Tests coverage ($coverage%) is greater than or equal to the threshold ($COVERAGE_THRESHOLD%). Tests passed!"
          else
            echo "Tests coverage ($coverage%) is below the threshold ($COVERAGE_THRESHOLD%). Tests failed!"
            exit 1
          fi